### ISSUE TITLE
What is the purpose of using both models（alpha_model and beta_model）

### ISSUE THREAD

**Issue by daihuiao** [armandli/ReconChessRL#2]
i cann't understand the code in rc_nfsp_trainner.py, it seems that you are using  two model to decide which one will choose the move in an episode ,what's the purpose???

**Comment by armandli** [comment]
it's the algorithm described in NFSP (Neural Fictitious Self Play) paper, where we train two models for the agent, one makes the best move, the other represent the agent's behavioral move.

**Comment by daihuiao** [comment]
Thank you for your reply
